apiVersion: v1
kind: Service
metadata:
  name: tomcat8store
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30081
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: tomcat8store
  sessionAffinity: None
  type: LoadBalancer
