apiVersion: v1
kind: Service
metadata:
  name: tomcat8store443
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30080
    name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - nodePort: 30443
    name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    run: tomcat8store
  sessionAffinity: None
  type: LoadBalancer
