apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    run: tomcat8store
  name: tomcat8store
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/tomcat8
spec:
  replicas: 1
  selector:
    matchLabels:
      run: tomcat8store
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: tomcat8store
    spec:
      containers:
      - image: registry.eu-de.bluemix.net/maks_s/tomcat-8.5:3
        imagePullPolicy: IfNotPresent
        name: tomcat8
        ports:
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-sqgw8
          readOnly: true
        - mountPath: /var/data
          name: tomcat-storage
      restartPolicy: Always
      volumes:
      - name: default-token-sqgw8
        secret:
          defaultMode: 420
          secretName: default-token-sqgw8
      - name: tomcat-storage
        persistentVolumeClaim:
          claimName: tomcat-volume-claim
      restartPolicy: Always
